name: Close all scheduled tasks with a 'Done' label which are in the past. Also close any items from Work Admin /Meetings section which are in the past, even if no 'Done' label is present
on:
  schedule:
    - cron: "30 10,14,18,22 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (if needed)
        run: npm ci
      - name: Run the script
        run: npm run close-tasks
        env:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}
